import { Lesson, DictionaryEntry, ExternalCourse } from "./types";

export const LESSONS: Lesson[] = [
  {
    id: "basics-1",
    title: "Basic Greetings & Politeness",
    description: "Learn how to welcome speakers, introduce yourself, and show gratitude in Kargili Purki/Purgi (with comparative Balti notes).",
    category: "basics",
    dialect: "both",
    difficulty: "Beginner",
    points: 100,
    steps: [
      {
        id: "greet-step-1",
        type: "content",
        title: "The Universal Greeting: Khamzang",
        text: `In the Kargili Purgi (Purki) language, greetings are deeply respectful. The universal phrase is **Khamzang** (sometimes spoken as *Khamzang thuk*).

Literally meaning **"Good health/state"** (derived from Classical Tibetan *kham* "element/health" + *zangpo* "good"), this is the most common way to greet anyone in the Kargil region.

To show deep respect, or when greeting elders, we say:
**"Khamzang thuk!"**

Alternatively, similar to Ladakhi, **"Joo"** or **"Joo joo"** is widely used in daily Kargili life as a versatile greeting, thank you, and farewell.`,
        audioText: "Khamzang thuk"
      },
      {
        id: "greet-step-2",
        type: "vocab",
        title: "Key Greetings Vocabulary",
        vocabItems: [
          {
            id: "vocab-khamzang",
            word: "Khamzang",
            tibetanScript: "ཁམས་བཟང་།",
            persoArabicScript: "خمزنگ",
            ipa: "/kʰam.zaŋ/",
            meaning: "Hello / Good morning / Well-being",
            urduMeaning: "سلام / خیریت",
            category: "Greetings",
            dialect: "both",
            notes: "Universal greeting. Derived from Old Tibetan khams (health) + bzang (good)."
          },
          {
            id: "vocab-joo",
            word: "Joo",
            tibetanScript: "ཇུ།",
            persoArabicScript: "جو",
            ipa: "/dʒuː/",
            meaning: "Hello / Thank you / Goodbye / Respectful particle",
            urduMeaning: "شکریہ / سلام / رخصت",
            category: "Greetings",
            dialect: "both",
            notes: "The ultimate multipurpose polite word. Equivalent to Ladakhi 'Ju'."
          },
          {
            id: "vocab-khas-kham",
            word: "Khas-kham yod-a?",
            tibetanScript: "ཁས་ཁམས་ཡོད་ད།",
            persoArabicScript: "خس خم یودا؟",
            ipa: "/kʰas.kʰam jo.da/",
            meaning: "How are you? (Literally: Is your health well?)",
            urduMeaning: "آپ کیسے ہیں؟",
            category: "Greetings",
            dialect: "balti",
            notes: "Specific Balti dialect expression for inquiry."
          },
          {
            id: "vocab-khamzang-yod",
            word: "Khamzang yod",
            tibetanScript: "ཁམས་བཟང་ཡོད།",
            persoArabicScript: "خمزنگ یود",
            ipa: "/kʰam.zaŋ jod/",
            meaning: "I am fine / I am well",
            urduMeaning: "میں ٹھیک ہوں",
            category: "Greetings",
            dialect: "both",
            notes: "Standard reply. 'yod' is the auxiliary verb for presence."
          }
        ]
      },
      {
        id: "greet-step-3",
        type: "quiz",
        title: "Greetings Quick Check",
        quizQuestion: "What is the historical Tibetan meaning of the greeting 'Khamzang'?",
        quizOptions: [
          "May the sun shine on you",
          "Good health / Elements in good state",
          "Welcome to our home",
          "Go in peace"
        ],
        quizAnswer: 1,
        quizExplanation: "Derived from Old Tibetan 'khams' (health/elements of the body) and 'bzang' (excellent/good)."
      }
    ]
  },
  {
    id: "phonology-1",
    title: "Archaic Consonant Clusters",
    description: "Discover why linguists love Kargili Purgi (Purki): they preserve ancient 1,200-year-old Tibetan consonant clusters!",
    category: "phonology",
    dialect: "both",
    difficulty: "Intermediate",
    points: 150,
    steps: [
      {
        id: "phone-step-1",
        type: "content",
        title: "Preservation of Classical Tibetan",
        text: `Modern Lhasa Tibetan has lost initial consonant clusters (such as **st-**, **sp-**, **sk-**, **br-**, **pr-**) and became a tonal language instead.

However, **Kargili Purgi (Purki) is non-tonal** and speaks these archaic consonant prefixes clearly! It serves as a living fossil of Classical Tibetan:
- The word for **"star"** was written as སྐར་མ་ (*skar-ma*) in classical Tibetan. In Lhasa, it is pronounced as tone-driven *karma*. In Purgi, it is still pronounced fully with the 's' cluster: **skarma**!
- The word for **"head"** was མགོ་ (*mgo*). In Purgi, it is spoken as **go**, retaining the voiced stop.
- The word for **"hand"** was ལག་པ་ (*lag-pa*). In Purgi, it is **lakpa**, keeping the final voiceless stop intact.`,
        audioText: "skarma, lakpa"
      },
      {
        id: "phone-step-2",
        type: "vocab",
        title: "Archaic Consonant Vocabulary",
        vocabItems: [
          {
            id: "vocab-skarma",
            word: "Skarma / Kar-ma",
            tibetanScript: "སྐར་མ།",
            persoArabicScript: "سکرمہ / کرمہ",
            ipa: "/skar.ma/",
            meaning: "Star",
            urduMeaning: "ستارہ",
            category: "Nature",
            dialect: "both",
            notes: "Directly preserves the Old Tibetan 'sk-' cluster. Lhasa Tibetan pronounces this simply as 'ka' with high tone."
          },
          {
            id: "vocab-lakpa",
            word: "Lakpa",
            tibetanScript: "ལག་པ།",
            persoArabicScript: "لقپا / لگپا",
            ipa: "/lak.pa/",
            meaning: "Hand",
            urduMeaning: "ہاتھ",
            category: "Body Parts",
            dialect: "both",
            notes: "Preserves the 'k' voiceless glottal offset written in classical Tibetan orthography."
          },
          {
            id: "vocab-rgyat",
            word: "Rgyat / Bgyat",
            tibetanScript: "བརྒྱད།",
            persoArabicScript: "رگیات / بگیات",
            ipa: "/rgjat/ /bgjat/",
            meaning: "Eight",
            urduMeaning: "آٹھ",
            category: "Numbers",
            dialect: "both",
            notes: "Highly complex. Purigi retains the 'rgy-' while Balti often pronounces it as 'bgy-' or 'gy-'."
          }
        ]
      },
      {
        id: "phone-step-3",
        type: "quiz",
        title: "Phonology Challenge",
        quizQuestion: "Which of the following describes why Balti and Purigi are unique among modern Tibetan languages?",
        quizOptions: [
          "They became fully tonal and lost all letters",
          "They are non-tonal and preserve ancient initial consonant clusters written in Classical Tibetan",
          "They use only English script with no regional script",
          "They are related to Latin instead of Sino-Tibetan"
        ],
        quizAnswer: 1,
        quizExplanation: "Linguists value Balti and Purigi as living fossils because they are non-tonal and preserve the initial consonant clusters of Classical Tibetan."
      }
    ]
  },
  {
    id: "grammar-1",
    title: "Grammatical Case Suffixes",
    description: "Master noun postpositions, dative markers, and the unique ergative case in Purgi sentences.",
    category: "grammar",
    dialect: "both",
    difficulty: "Intermediate",
    points: 150,
    steps: [
      {
        id: "gram-step-1",
        type: "content",
        title: "The Four Core Noun Cases",
        text: `In the Purgi language of Kargil, relation markers (postpositions) are attached directly to nouns as suffixes:

1. **Nominative (Subject)**: Unmarked. (e.g. *Aba* = Father)
2. **Genitive (Possessive) \`-i\` or \`-gi\`**: Indicates ownership.
   - *Aba-i nang* = Father's house.
   - *nga-i ming* = My name.
3. **Dative / Locative \`-la\`**: Means 'to', 'at', 'in'.
   - *nang-la* = In the house / at home.
   - *nga-la cha chin* = Give to me.
4. **Ergative / Agentive \`-is\` or \`-gis\`**: Used when the subject performs a transitive past action.
   - *Aba-is zan zos* = Father ate the food. (Aba is marked with *is* because eating is a transitive past action!).`,
        audioText: "Abai nang, nangla, Abais zan zos"
      },
      {
        id: "gram-step-2",
        type: "vocab",
        title: "Grammar Suffix Examples",
        vocabItems: [
          {
            id: "vocab-abai",
            word: "Aba-i",
            tibetanScript: "ཨ་བའི།",
            persoArabicScript: "ابئی",
            ipa: "/a.ba.i/",
            meaning: "Father's (Genitive)",
            urduMeaning: "والد کا",
            category: "Grammar Suffix",
            dialect: "both",
            notes: "Suffix -i denotes possessive relation."
          },
          {
            id: "vocab-nangla",
            word: "Nang-la",
            tibetanScript: "ནང་ལ།",
            persoArabicScript: "ننگ لا",
            ipa: "/naŋ.la/",
            meaning: "In/at the house (Dative/Locative)",
            urduMeaning: "گھر میں",
            category: "Grammar Suffix",
            dialect: "both",
            notes: "Suffix -la functions as postposition for location."
          },
          {
            id: "vocab-ngais",
            word: "Nga-is",
            tibetanScript: "ང་ཡིས།",
            persoArabicScript: "نگئیس",
            ipa: "/ŋa.is/",
            meaning: "By me (Ergative)",
            urduMeaning: "میں نے",
            category: "Grammar Suffix",
            dialect: "both",
            notes: "Suffix -is denotes agentive subject performing past action."
          }
        ]
      },
      {
        id: "gram-step-3",
        type: "quiz",
        title: "Ergative Suffix Quiz",
        quizQuestion: "In the sentence 'Aba-is zan zos' (Father ate food), why does 'Aba' become 'Aba-is'?",
        quizOptions: [
          "Because father owns the food",
          "Because father is in the house",
          "Because father is the active agent performing a past transitive action (eating)",
          "To indicate plural fathers"
        ],
        quizAnswer: 2,
        quizExplanation: "The ergative suffix -is or -gis is attached to active subjects of transitive verbs in past-aspect clauses."
      }
    ]
  },
  {
    id: "conversations-1",
    title: "Asking for Names & Origins",
    description: "Learn how to ask people their names, where they come from, and hold a clean starting convo.",
    category: "conversations",
    dialect: "both",
    difficulty: "Beginner",
    points: 100,
    steps: [
      {
        id: "conv-step-1",
        type: "content",
        title: "Polite Dialogue",
        text: `Let's see how two speakers meet for the first time in Baltistan or Kargil:

**Speaker A:** Khamzang thuk! (*Hello!*)
**Speaker B:** Khamzang! (*Hello!*)

**Speaker A:** Nyeri ming-la chi in? (*What is your name? - Polite*)
**Speaker B:** Nga-i ming Ali in. Khyang-gi ming chi in? (*My name is Ali. What is your name?*)

**Speaker A:** Nga-i ming Fatima in. Khyang khari-ba in? (*My name is Fatima. Where are you from?*)
**Speaker B:** Nga Skardu-ne in. (*I am from Skardu.*) Or: *Nga Kargil-ne in.* (*I am from Kargil.*)`,
        audioText: "Nyeri mingla chi in, Ngai ming Ali in"
      },
      {
        id: "conv-step-2",
        type: "vocab",
        title: "Dialog Particles",
        vocabItems: [
          {
            id: "vocab-nyeri",
            word: "Nyer-i",
            tibetanScript: "ཉེར་གྱི།",
            persoArabicScript: "نیری",
            ipa: "/ɲer.i/",
            meaning: "Your (Honorific / Polite)",
            urduMeaning: "آپ کا",
            category: "Pronouns",
            dialect: "both",
            notes: "Used with elders or new acquaintances."
          },
          {
            id: "vocab-khang",
            word: "Khyang",
            tibetanScript: "ཁྱང་།",
            persoArabicScript: "کھیانگ",
            ipa: "/kʰjaŋ/",
            meaning: "You (Standard)",
            urduMeaning: "تم",
            category: "Pronouns",
            dialect: "both",
            notes: "Used with friends or peers."
          },
          {
            id: "vocab-khari",
            word: "Khari-ba / Khaye-ba",
            tibetanScript: "ཁ་རི་བ།",
            persoArabicScript: "کھاری با",
            ipa: "/kʰa.ri.ba/",
            meaning: "From where?",
            urduMeaning: "کہاں سے؟",
            category: "Question words",
            dialect: "both",
            notes: "Balti uses 'khari-ba', Purik often uses 'khaye-ba'."
          }
        ]
      },
      {
        id: "conv-step-3",
        type: "quiz",
        title: "Pronoun Quiz",
        quizQuestion: "What is the polite honorific pronoun for 'You' in Balti and Purigi?",
        quizOptions: [
          "Khyang",
          "Nyer",
          "Kho",
          "Mo"
        ],
        quizAnswer: 1,
        quizExplanation: "'Nyer' (genitive 'Nyeri') is the respectful, honorific word for 'You', whereas 'Khyang' is the standard, informal word."
      }
    ]
  }
];

export const DICTIONARY: DictionaryEntry[] = [
  {
    id: "dict-khamzang",
    word: "Khamzang",
    tibetanScript: "ཁམས་བཟང་།",
    persoArabicScript: "خمزنگ",
    ipa: "/kʰam.zaŋ/",
    meaning: "Greetings, well-being, safe and sound, peaceful",
    urduMeaning: "سلام، سلامتی، خیریت",
    partOfSpeech: "Noun / Interjection",
    dialect: "common",
    definition: "An ancient greeting term shared across Balti, Purigi, and Ladakhi. Translates to 'in good health/elements'. Used to wish peace or check someone's condition.",
    exampleSentence: "Khamzang yod-a, Aba?",
    exampleTranslation: "Are you well, Father?",
    etymology: "From Old Tibetan 'khams' (physical health) + 'bzang' (fine/virtuous)."
  },
  {
    id: "dict-joo",
    word: "Joo",
    tibetanScript: "ཇུ།",
    persoArabicScript: "جو",
    ipa: "/dʒuː/",
    meaning: "Multi-purpose particle: Hello, Thank you, Goodbye",
    urduMeaning: "شکریہ، سلام، الوداع",
    partOfSpeech: "Interjection",
    dialect: "common",
    definition: "An honorary conversational particle that signifies respect, appreciation, or leave-taking. Highly typical of Himalayan Baltistan and Ladakh language regions.",
    exampleSentence: "Joo joo, nga-i butsa.",
    exampleTranslation: "Thank you, my son.",
    etymology: "A regional honorific morpheme, linked to classic Central Asian respectful responses."
  },
  {
    id: "dict-aba",
    word: "Aba",
    tibetanScript: "ཨ་བ།",
    persoArabicScript: "ابا",
    ipa: "/a.ba/",
    meaning: "Father",
    urduMeaning: "والد / ابا",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Primary family word referring to father. In honorific speech, sometimes suffixed as 'Aba-le'.",
    exampleSentence: "Aba-is khambir zos.",
    exampleTranslation: "Father ate the traditional bread.",
    etymology: "Proto-Tibeto-Burman kinship vocalization."
  },
  {
    id: "dict-ama",
    word: "Ama",
    tibetanScript: "ཨ་མ།",
    persoArabicScript: "امّا",
    ipa: "/a.ma/",
    meaning: "Mother",
    urduMeaning: "والدہ / امی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Kinship term for mother, widely used across Kargil, Leh, and Baltistan valleys. Suffix '-le' makes it honorific ('Ama-le').",
    exampleSentence: "Ama-la tsha cha chin.",
    exampleTranslation: "Give salt to Mother.",
    etymology: "Old Tibetan 'ma'."
  },
  {
    id: "dict-ape",
    word: "Ape",
    tibetanScript: "ཨ་ཕྱི།",
    persoArabicScript: "اپے",
    ipa: "/a.pe/",
    meaning: "Grandfather",
    urduMeaning: "دادا / نانا",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Purki kinship term for grandfather. Also used respectfully for elderly male community members in Kargil.",
    exampleSentence: "Ape-is khurba zos.",
    exampleTranslation: "Grandfather ate the bread.",
    etymology: "Related to Classical Tibetan 'a-phyi' (grandmother/elder)."
  },
  {
    id: "dict-momo",
    word: "Momo",
    tibetanScript: "མོ་མོ།",
    persoArabicScript: "مومو",
    ipa: "/mo.mo/",
    meaning: "Grandmother",
    urduMeaning: "دادی / نانی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Affectionate maternal and paternal kinship term for grandmother.",
    exampleSentence: "Momo-la khamzang thuk.",
    exampleTranslation: "Greetings to Grandmother.",
    etymology: "Himalayan Tibetan honorific nursery word."
  },
  {
    id: "dict-butsa",
    word: "Butsa",
    tibetanScript: "བུ་ཚ།",
    persoArabicScript: "بچا",
    ipa: "/bu.tsa/",
    meaning: "Boy / Son",
    urduMeaning: "لڑکا / بیٹا",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Refers to a young male child or a biological son.",
    exampleSentence: "Nga-la butsa chik yod.",
    exampleTranslation: "I have one son.",
    etymology: "From Classical Tibetan 'bu' (boy/son) + 'tsha' (grandchild/descendant)."
  },
  {
    id: "dict-bumo",
    word: "Bumo",
    tibetanScript: "བུ་མོ།",
    persoArabicScript: "بومو",
    ipa: "/bu.mo/",
    meaning: "Girl / Daughter",
    urduMeaning: "لڑکی / بیٹی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Refers to a young female child or biological daughter.",
    exampleSentence: "Khyang-la bumo sum yod-a?",
    exampleTranslation: "Do you have three daughters?",
    etymology: "Classical Tibetan 'bu-mo' (daughter)."
  },
  {
    id: "dict-nao",
    word: "Nao",
    tibetanScript: "ནུ་བོ།",
    persoArabicScript: "ناو",
    ipa: "/na.o/",
    meaning: "Younger Brother",
    urduMeaning: "چھوٹا بھائی",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Refers to a younger male sibling in Purgi households.",
    exampleSentence: "Nga-i nao skul-la song.",
    exampleTranslation: "My younger brother went to school.",
    etymology: "Classical Tibetan 'nu-bo'."
  },
  {
    id: "dict-nama",
    word: "Nama",
    tibetanScript: "མནའ་མ།",
    persoArabicScript: "ناما",
    ipa: "/na.ma/",
    meaning: "Bride / Daughter-in-law",
    urduMeaning: "دلہن / بہو",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Kinship term for daughter-in-law or newly wed bride.",
    exampleSentence: "Nama nang-la ongis.",
    exampleTranslation: "The bride has entered the house.",
    etymology: "Old Tibetan 'mna'-ma'."
  },
  {
    id: "dict-mi",
    word: "Mi",
    tibetanScript: "མི།",
    persoArabicScript: "می",
    ipa: "/mi/",
    meaning: "Man / Person / Human",
    urduMeaning: "آدمی / انسان",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "A person or human being.",
    exampleSentence: "Nang-la mi nis yod.",
    exampleTranslation: "There are two people in the house.",
    etymology: "Sino-Tibetan root '*myit' / Classical Tibetan 'mi'."
  },
  {
    id: "dict-skarma",
    word: "Skarma",
    tibetanScript: "སྐར་མ།",
    persoArabicScript: "سکرمہ",
    ipa: "/skar.ma/",
    meaning: "Star",
    urduMeaning: "ستارہ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Celestial stellar object. A premier example of archaic consonant retention ('sk-') in modern Tibeto-Burman phonology.",
    exampleSentence: "Nam-la skarma mangpo yod.",
    exampleTranslation: "There are many stars in the sky.",
    etymology: "Old Tibetan 'skar-ma'. Tone-dependent in Standard Lhasa, but retains clusters in Balti and Purigi."
  },
  {
    id: "dict-lakpa",
    word: "Lakpa",
    tibetanScript: "ལག་པ།",
    persoArabicScript: "لقپا / لگپا",
    ipa: "/lak.pa/",
    meaning: "Hand / Arm",
    urduMeaning: "ہاتھ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "The upper limb of the human body. Retains the ancient final 'k' voiceless glottal stop sound.",
    exampleSentence: "Khyang-gi lakpa thsokpo yo.",
    exampleTranslation: "Your hand is beautiful.",
    etymology: "Old Tibetan 'lag-pa'."
  },
  {
    id: "dict-kanga",
    word: "Kanga",
    tibetanScript: "རྐང་པ།",
    persoArabicScript: "کانگا",
    ipa: "/kaŋ.ga/",
    meaning: "Foot / Leg",
    urduMeaning: "پاؤں",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Lower limb or foot. Features the archaic 'rk-' prefix preservation pronounced as k-voiceless or k-voiced cluster.",
    exampleSentence: "Kanga-la tsherma tsuks-pa.",
    exampleTranslation: "A thorn pricked my foot.",
    etymology: "Classical Tibetan 'rkang-pa'."
  },
  {
    id: "dict-go",
    word: "Go",
    tibetanScript: "མགོ།",
    persoArabicScript: "گو",
    ipa: "/go/",
    meaning: "Head",
    urduMeaning: "سر",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "The head of a human or animal. Derives from a prefixed classical root where the prefix voiced stop is dropped but leaves the main voiced stop.",
    exampleSentence: "Nga-i go-la thsa-gzer yod.",
    exampleTranslation: "My head hurts / I have a headache.",
    etymology: "Classical Tibetan 'mgo'."
  },
  {
    id: "dict-mik",
    word: "Mik",
    tibetanScript: "མིག།",
    persoArabicScript: "مک",
    ipa: "/mik/",
    meaning: "Eye",
    urduMeaning: "آنکھ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Human eye or sense of vision. Retains final -g stop pronunciation as a voiceless stop.",
    exampleSentence: "Mik nis gnyid-is zim-pa.",
    exampleTranslation: "Both eyes closed in sleep.",
    etymology: "Classical Tibetan 'mig' / 'migs'."
  },
  {
    id: "dict-hrna",
    word: "Hrna",
    tibetanScript: "སྣ།",
    persoArabicScript: "ہرنا",
    ipa: "/rna/",
    meaning: "Nose",
    urduMeaning: "ناک",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Nose. Retains the ancient retroflex/aspirated or voiceless nasal sound typified by the 's-' prefix in classical orthography.",
    exampleSentence: "Hrna-la thsaldum babs.",
    exampleTranslation: "Blood came from the nose.",
    etymology: "Classical Tibetan 'sna'."
  },
  {
    id: "dict-hrnachu",
    word: "Hrna-chhu",
    tibetanScript: "སྣ་ཆུ།",
    persoArabicScript: "ہرناچو",
    ipa: "/rna.tʃu/",
    meaning: "Mucus / Nasal discharge",
    urduMeaning: "ناک کا پانی",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Literal compound of 'nose' (hrna) and 'water' (chhu).",
    exampleSentence: "Hrna-chhu babs-ches re.",
    exampleTranslation: "Nasal water is running.",
    etymology: "Classical Tibetan 'sna-chu'."
  },
  {
    id: "dict-rnaba",
    word: "Rna-ba",
    tibetanScript: "རྣ་བ།",
    persoArabicScript: "رنابا",
    ipa: "/rna.ba/",
    meaning: "Ear",
    urduMeaning: "کان",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "The auditory organ of hearing.",
    exampleSentence: "Rna-ba-is thos-pa.",
    exampleTranslation: "The ear heard.",
    etymology: "Classical Tibetan 'rna-ba'."
  },
  {
    id: "dict-kha",
    word: "Kha",
    tibetanScript: "ཁ།",
    persoArabicScript: "کھا",
    ipa: "/kʰa/",
    meaning: "Mouth",
    urduMeaning: "منہ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Mouth. Used in multiple idioms such as 'kha-thak' (silent) or 'kha-zang' (honest speech).",
    exampleSentence: "Kha thong!",
    exampleTranslation: "Open your mouth!",
    etymology: "Classical Tibetan 'kha'."
  },
  {
    id: "dict-so",
    word: "So",
    tibetanScript: "སོ།",
    persoArabicScript: "سو",
    ipa: "/so/",
    meaning: "Tooth",
    urduMeaning: "دانت",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Tooth or teeth.",
    exampleSentence: "So-la thsa-gzer babs-pa.",
    exampleTranslation: "Got a toothache.",
    etymology: "Classical Tibetan 'so'."
  },
  {
    id: "dict-lche",
    word: "Lche",
    tibetanScript: "ལྕེ།",
    persoArabicScript: "لچے",
    ipa: "/ltʃe/",
    meaning: "Tongue",
    urduMeaning: "زبان",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "The muscular organ of taste and speech, keeping the archaic 'lc-' cluster intact.",
    exampleSentence: "Lche thon-ba.",
    exampleTranslation: "Stick out your tongue.",
    etymology: "Classical Tibetan 'lce'."
  },
  {
    id: "dict-spu",
    word: "Spu",
    tibetanScript: "སྤུ།",
    persoArabicScript: "سپو",
    ipa: "/spu/",
    meaning: "Hair / Fur / Feather",
    urduMeaning: "بال",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Body hair or fleece, retaining the unvoiced bilabial stop with 's' cluster prefix.",
    exampleSentence: "Khuyi-i spu karpo yo.",
    exampleTranslation: "The dog's fur is white.",
    etymology: "Classical Tibetan 'spu'."
  },
  {
    id: "dict-chu",
    word: "Chu",
    tibetanScript: "ཆུ།",
    persoArabicScript: "چو",
    ipa: "/tʃuː/",
    meaning: "Water / Liquid",
    urduMeaning: "پانی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Water. Essential lexical item. Often compound forms like 'chu-mran' (water spring) or 'chu-tsan' (hot water).",
    exampleSentence: "Nga-la chu thung-chas in.",
    exampleTranslation: "I want to drink water.",
    etymology: "Proto-Tibeto-Burman '*tsyiy'."
  },
  {
    id: "dict-me",
    word: "Me",
    tibetanScript: "མེ།",
    persoArabicScript: "مے",
    ipa: "/me/",
    meaning: "Fire",
    urduMeaning: "آگ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Fire or flame.",
    exampleSentence: "Me spar!",
    exampleTranslation: "Light the fire!",
    etymology: "Classical Tibetan 'me'."
  },
  {
    id: "dict-lungpo",
    word: "Lungpo",
    tibetanScript: "རླུང་པོ།",
    persoArabicScript: "لونگپو",
    ipa: "/luŋ.po/",
    meaning: "Wind / Air current",
    urduMeaning: "ہوا",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Strong mountain wind, keeping the ancient 'rl-' phoneme pronounced as a velar or lateral fricative.",
    exampleSentence: "Lungpo tshanmo gyap-pa.",
    exampleTranslation: "Warm wind is blowing.",
    etymology: "Classical Tibetan 'rlung-po'."
  },
  {
    id: "dict-sa",
    word: "Sa",
    tibetanScript: "ས།",
    persoArabicScript: "سا",
    ipa: "/sa/",
    meaning: "Earth / Soil / Land",
    urduMeaning: "زمین / مٹی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "The ground, earth, or a plot of land.",
    exampleSentence: "Sa-la duk!",
    exampleTranslation: "Sit on the ground!",
    etymology: "Classical Tibetan 'sa'."
  },
  {
    id: "dict-ri",
    word: "Ri",
    tibetanScript: "རི།",
    persoArabicScript: "ری",
    ipa: "/ri/",
    meaning: "Mountain",
    urduMeaning: "پہاڑ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "A mountain or high peak, typical feature of Ladakh's landscape.",
    exampleSentence: "Kargil-gi ri-la kha-ba babs.",
    exampleTranslation: "Snow fell on the mountains of Kargil.",
    etymology: "Classical Tibetan 'ri'."
  },
  {
    id: "dict-la",
    word: "La",
    tibetanScript: "ལ།",
    persoArabicScript: "لا",
    ipa: "/la/",
    meaning: "Mountain Pass",
    urduMeaning: "درہ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "A high mountain pass connecting valleys (e.g. Zoji La, Fotu La).",
    exampleSentence: "La thon-ba bka-mo yo.",
    exampleTranslation: "Crossing the mountain pass is difficult.",
    etymology: "Classical Tibetan 'la'."
  },
  {
    id: "dict-khaba",
    word: "Kha-ba",
    tibetanScript: "ཁ་བ།",
    persoArabicScript: "کھابا",
    ipa: "/kʰa.ba/",
    meaning: "Snow",
    urduMeaning: "برف",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Snow. A crucial winter lexical item in regional vocabularies.",
    exampleSentence: "Kha-ba mangpo babs.",
    exampleTranslation: "A lot of snow fell.",
    etymology: "Classical Tibetan 'kha-ba'."
  },
  {
    id: "dict-rgyatso",
    word: "Rgya-tso",
    tibetanScript: "རྒྱ་མཚོ།",
    persoArabicScript: "رگیاتسو",
    ipa: "/rgja.tso/",
    meaning: "Ocean / Sea / Large Lake",
    urduMeaning: "سمندر / جھیل",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Large water bodies. Retains prefixed cluster 'rgy-'.",
    exampleSentence: "Rgya-tso tschena re.",
    exampleTranslation: "The ocean is vast.",
    etymology: "Classical Tibetan 'rgya-mtsho'."
  },
  {
    id: "dict-ta",
    word: "Ta",
    tibetanScript: "རྟ།",
    persoArabicScript: "تا",
    ipa: "/ta/",
    meaning: "Horse",
    urduMeaning: "گھوڑا",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Horse. Retains the prefix 'rt-' in written Tibetan, pronounced as a voiceless retroflex or dental stop in Purgi.",
    exampleSentence: "Ta-la zhon-ba.",
    exampleTranslation: "To ride a horse.",
    etymology: "Classical Tibetan 'rta'."
  },
  {
    id: "dict-khuyi",
    word: "Khuyi",
    tibetanScript: "ཁྱི།",
    persoArabicScript: "کھوئی",
    ipa: "/kʰu.ji/",
    meaning: "Dog",
    urduMeaning: "کتا",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Dog. The genitive is 'khuyi-i' (of the dog).",
    exampleSentence: "Khuyi nang-gi sgo-la yod.",
    exampleTranslation: "The dog is at the door of the house.",
    etymology: "Classical Tibetan 'khyi'."
  },
  {
    id: "dict-bila",
    word: "Bila",
    tibetanScript: "བྱི་ལ།",
    persoArabicScript: "بیلا",
    ipa: "/bi.la/",
    meaning: "Cat",
    urduMeaning: "بلی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "A domestic cat.",
    exampleSentence: "Bila-is oma thungs.",
    exampleTranslation: "The cat drank milk.",
    etymology: "Classical Tibetan 'byi-la'."
  },
  {
    id: "dict-bal",
    word: "Bal",
    tibetanScript: "བལ།",
    persoArabicScript: "بال",
    ipa: "/bal/",
    meaning: "Wool",
    urduMeaning: "اون",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Sheep wool, crucial local material for warm woolen blankets and clothing (pattu).",
    exampleSentence: "Bal-i gonchas.",
    exampleTranslation: "Woolen clothes.",
    etymology: "Classical Tibetan 'bal'."
  },
  {
    id: "dict-lakh",
    word: "Lakh",
    tibetanScript: "ལུག།",
    persoArabicScript: "لکھ / لک",
    ipa: "/lak/",
    meaning: "Sheep",
    urduMeaning: "بھیڑ",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Sheep. Retains final -g stop pronounced as -kh or -k in Purki, as studied by D.N.S. Bhat.",
    exampleSentence: "Lakh-is rtsa zos.",
    exampleTranslation: "The sheep ate grass.",
    etymology: "Classical Tibetan 'lug'."
  },
  {
    id: "dict-ra",
    word: "Ra",
    tibetanScript: "ར།",
    persoArabicScript: "را",
    ipa: "/ra/",
    meaning: "Goat",
    urduMeaning: "بکری",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Goat, major livestock animal in high Ladakh valleys.",
    exampleSentence: "Ra-i rba.",
    exampleTranslation: "Goat's milk.",
    etymology: "Classical Tibetan 'ra' / 'ra-ma'."
  },
  {
    id: "dict-phalo",
    word: "Phalo",
    tibetanScript: "གླང་།",
    persoArabicScript: "پھالو",
    ipa: "/pʰa.lo/",
    meaning: "Bull / Ox",
    urduMeaning: "بیل",
    partOfSpeech: "Noun",
    dialect: "purigi",
    definition: "Bull or ox used for ploughing valley terraced fields.",
    exampleSentence: "Phalo-is field rmos.",
    exampleTranslation: "The ox ploughed the field.",
    etymology: "Sino-Tibetan agricultural terms."
  },
  {
    id: "dict-bja",
    word: "Bja",
    tibetanScript: "བྱ།",
    persoArabicScript: "بجا / بیا",
    ipa: "/bja/",
    meaning: "Bird",
    urduMeaning: "پرندہ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "A bird. Preserves the archaic bilabial-palatal cluster 'by-' as 'bj-' or 'by-'.",
    exampleSentence: "Bja ri-la phur-is.",
    exampleTranslation: "The bird flew to the mountain.",
    etymology: "Classical Tibetan 'bya'."
  },
  {
    id: "dict-nja",
    word: "Nja",
    tibetanScript: "ཉ།",
    persoArabicScript: "نجا / نیا",
    ipa: "/ɲa/",
    meaning: "Fish",
    urduMeaning: "مچھلی",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Fish.",
    exampleSentence: "Nja chu-la duk-pa.",
    exampleTranslation: "The fish stays in the water.",
    etymology: "Classical Tibetan 'nya'."
  },
  {
    id: "dict-sgo",
    word: "Sgo",
    tibetanScript: "སྒོ།",
    persoArabicScript: "سگو",
    ipa: "/sgo/",
    meaning: "Door / Gate",
    urduMeaning: "دروازہ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "The door of a building or room, keeping the archaic 'sg-' cluster pronounced.",
    exampleSentence: "Sgo thsogs!",
    exampleTranslation: "Shut the door!",
    etymology: "Classical Tibetan 'sgo'."
  },
  {
    id: "dict-thap",
    word: "Thap",
    tibetanScript: "ཐབ།",
    persoArabicScript: "تھپ",
    ipa: "/tʰap/",
    meaning: "Stove / Hearth / Cooking fireplace",
    urduMeaning: "چولہا",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Hearth or stove which is the center of Ladakhi family homes.",
    exampleSentence: "Thap-la me spar!",
    exampleTranslation: "Light fire in the hearth!",
    etymology: "Classical Tibetan 'thab' (fireplace)."
  },
  {
    id: "dict-turmang",
    word: "Turmang",
    tibetanScript: "ཐུར་མ།",
    persoArabicScript: "تورمنگ",
    ipa: "/tur.maŋ/",
    meaning: "Spoon",
    urduMeaning: "چمچ",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Household spoon.",
    exampleSentence: "Nga-la turmang chik chin.",
    exampleTranslation: "Give me a spoon.",
    etymology: "Classical Tibetan 'thur-ma' with nasal nominal suffix."
  },
  {
    id: "dict-tsampa",
    word: "Tsampa",
    tibetanScript: "རྩམ་པ།",
    persoArabicScript: "تسمپا / ستو",
    ipa: "/tsam.pa/",
    meaning: "Roasted barley flour",
    urduMeaning: "ستو",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Roasted barley flour, eaten daily mixed with salted butter tea.",
    exampleSentence: "Nga-is tsampa thungs.",
    exampleTranslation: "I ate/drank tsampa (porridge).",
    etymology: "Classical Tibetan 'rtsam-pa'."
  },
  {
    id: "dict-cha",
    word: "Cha",
    tibetanScript: "ཇ།",
    persoArabicScript: "چائے / جا",
    ipa: "/dʒa/",
    meaning: "Tea / Salt tea",
    urduMeaning: "چائے",
    partOfSpeech: "Noun",
    dialect: "common",
    definition: "Tea. Frequently refers to traditional salty butter tea (gurgur cha).",
    exampleSentence: "Cha thung!",
    exampleTranslation: "Drink tea!",
    etymology: "Sino-Tibetan cognates."
  },
  {
    id: "dict-chik",
    word: "Chik",
    tibetanScript: "གཅིག།",
    persoArabicScript: "چک",
    ipa: "/tʃik/",
    meaning: "One",
    urduMeaning: "ایک",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number one.",
    exampleSentence: "Butsa chik ongis.",
    exampleTranslation: "One boy came.",
    etymology: "Classical Tibetan 'gcig'."
  },
  {
    id: "dict-nis",
    word: "Nis",
    tibetanScript: "གཉིས།",
    persoArabicScript: "نس",
    ipa: "/nis/",
    meaning: "Two",
    urduMeaning: "دو",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number two.",
    exampleSentence: "Kanga nis.",
    exampleTranslation: "Two feet.",
    etymology: "Classical Tibetan 'gnyis'."
  },
  {
    id: "dict-sum",
    word: "Sum",
    tibetanScript: "གསུམ།",
    persoArabicScript: "سم",
    ipa: "/sum/",
    meaning: "Three",
    urduMeaning: "تین",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number three.",
    exampleSentence: "Mi sum yod.",
    exampleTranslation: "There are three people.",
    etymology: "Classical Tibetan 'gsum'."
  },
  {
    id: "dict-bzhi",
    word: "Bzhi",
    tibetanScript: "བཞི།",
    persoArabicScript: "بژی",
    ipa: "/bʒi/",
    meaning: "Four",
    urduMeaning: "چار",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number four, pronounced with voiced retroflex fricative.",
    exampleSentence: "Ta bzhi.",
    exampleTranslation: "Four horses.",
    etymology: "Classical Tibetan 'bzhi'."
  },
  {
    id: "dict-gnga",
    word: "Gnga",
    tibetanScript: "ལྔ།",
    persoArabicScript: "غنگا",
    ipa: "/ŋa/",
    meaning: "Five",
    urduMeaning: "پانچ",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number five, retaining a velar nasal pronunciation.",
    exampleSentence: "Lakpa gnga.",
    exampleTranslation: "Five hands/fingers.",
    etymology: "Classical Tibetan 'lnga'."
  },
  {
    id: "dict-truk",
    word: "Truk",
    tibetanScript: "དྲུག།",
    persoArabicScript: "ٹرک",
    ipa: "/truk/",
    meaning: "Six",
    urduMeaning: "چھ",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number six.",
    exampleSentence: "Bumo truk skul-la song.",
    exampleTranslation: "Six girls went to school.",
    etymology: "Classical Tibetan 'drug'."
  },
  {
    id: "dict-bdun",
    word: "Bdun",
    tibetanScript: "བདུན།",
    persoArabicScript: "بدن",
    ipa: "/bdun/",
    meaning: "Seven",
    urduMeaning: "سات",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number seven, preserving the initial bilabial stop prefix b-.",
    exampleSentence: "Nyima bdun.",
    exampleTranslation: "Seven days.",
    etymology: "Classical Tibetan 'bdun'."
  },
  {
    id: "dict-rgyat",
    word: "Rgyat",
    tibetanScript: "བརྒྱད།",
    persoArabicScript: "رگیات",
    ipa: "/rgjat/",
    meaning: "Eight",
    urduMeaning: "آٹھ",
    partOfSpeech: "Numeral",
    dialect: "purigi",
    definition: "The cardinal number eight.",
    exampleSentence: "Skarma rgyat nam-la yod.",
    exampleTranslation: "Eight stars are in the sky.",
    etymology: "Classical Tibetan 'brgyad'."
  },
  {
    id: "dict-rgu",
    word: "Rgu",
    tibetanScript: "དགུ།",
    persoArabicScript: "رگو",
    ipa: "/rgu/",
    meaning: "Nine",
    urduMeaning: "نو",
    partOfSpeech: "Numeral",
    dialect: "common",
    definition: "The number nine.",
    exampleSentence: "Khuyi rgu.",
    exampleTranslation: "Nine dogs.",
    etymology: "Classical Tibetan 'dgu'."
  },
  {
    id: "dict-hchustham",
    word: "Hchustham",
    tibetanScript: "བཅུ།",
    persoArabicScript: "ہچوستھم",
    ipa: "/htʃus.tʰam/",
    meaning: "Ten",
    urduMeaning: "دس",
    partOfSpeech: "Numeral",
    dialect: "purigi",
    definition: "The number ten.",
    exampleSentence: "Mi hchustham yod.",
    exampleTranslation: "There are ten people.",
    etymology: "Classical Tibetan 'bcu-tham-pa'."
  },
  {
    id: "dict-zochas",
    word: "Zo-chas",
    tibetanScript: "ཟ་བ།",
    persoArabicScript: "زوچس",
    ipa: "/zo.tʃas/",
    meaning: "To eat",
    urduMeaning: "کھانا",
    partOfSpeech: "Verb (Infinitive)",
    dialect: "purigi",
    definition: "The action of consuming food. Ends in Purgi infinitive ending '-chas' as highlighted by D.N.S. Bhat.",
    exampleSentence: "Nga khurba zo-chas in.",
    exampleTranslation: "I want to eat bread.",
    etymology: "Classical Tibetan 'za-ba'."
  },
  {
    id: "dict-thungchas",
    word: "Thung-chas",
    tibetanScript: "འཐུང་བ།",
    persoArabicScript: "تھونگچس",
    ipa: "/tʰuŋ.tʃas/",
    meaning: "To drink",
    urduMeaning: "پینا",
    partOfSpeech: "Verb (Infinitive)",
    dialect: "purigi",
    definition: "The action of drinking liquids.",
    exampleSentence: "Nga-la chu thung-chas in.",
    exampleTranslation: "I want to drink water.",
    etymology: "Classical Tibetan 'thung-ba'."
  },
  {
    id: "dict-chachas",
    word: "Cha-chas",
    tibetanScript: "འགྲོ་བ།",
    persoArabicScript: "چاچس",
    ipa: "/tʃa.tʃas/",
    meaning: "To go",
    urduMeaning: "جانا",
    partOfSpeech: "Verb (Infinitive)",
    dialect: "purigi",
    definition: "The action of walking or travelling away.",
    exampleSentence: "Kho Kargil-la cha-chas in.",
    exampleTranslation: "He wants to go to Kargil.",
    etymology: "Classical Tibetan 'gro-ba' / 'cha-ba'."
  },
  {
    id: "dict-ongchas",
    word: "Ong-chas",
    tibetanScript: "ཡོང་བ།",
    persoArabicScript: "اونگچس",
    ipa: "/oŋ.tʃas/",
    meaning: "To come",
    urduMeaning: "آنا",
    partOfSpeech: "Verb (Infinitive)",
    dialect: "purigi",
    definition: "The action of arriving or coming toward.",
    exampleSentence: "Nama nang-la ong-is.",
    exampleTranslation: "The bride came into the house.",
    etymology: "Classical Tibetan 'yong-ba'."
  },
  {
    id: "dict-ltapchas",
    word: "Ltap-chas / Lta-chas",
    tibetanScript: "ལྟ་བ།",
    persoArabicScript: "لتاپچس",
    ipa: "/ltap.tʃas/",
    meaning: "To look / To see",
    urduMeaning: "دیکھنا",
    partOfSpeech: "Verb (Infinitive)",
    dialect: "purigi",
    definition: "To see or watch. Keeps the voiceless alveolar-dental cluster 'lt-'.",
    exampleSentence: "Ri-la ltap-chas.",
    exampleTranslation: "To look at the mountain.",
    etymology: "Classical Tibetan 'lta-ba'."
  },
  {
    id: "dict-sheschas",
    word: "Shes-chas",
    tibetanScript: "ཤེས་པ།",
    persoArabicScript: "شیسچس",
    ipa: "/ʃes.tʃas/",
    meaning: "To know / understand",
    urduMeaning: "جاننا",
    partOfSpeech: "Verb (Infinitive)",
    dialect: "purigi",
    definition: "To possess knowledge or comprehension.",
    exampleSentence: "Nga-is Purgi shes-chas in.",
    exampleTranslation: "I know the Purgi language.",
    etymology: "Classical Tibetan 'shes-pa'."
  }
];

export const EXTERNAL_RESOURCES: any[] = [
  {
    id: "res-purki-grammar-bhat",
    title: "Purki Grammar (1974) by D.N.S. Bhat",
    provider: "Archive.org",
    description: "The pioneering, comprehensive grammatical and phonological study of the Purki (Purgi) language spoken in Kargil district, Ladakh. Published by the Central Institute of Indian Languages.",
    url: "https://archive.org/details/dli.language.2277/page/n23/mode/1up",
    tags: ["Purki Grammar", "Phonology", "CIIL", "Archaic Tibetan"],
    level: "Archival"
  },
  {
    id: "coursera-ling-intro",
    title: "Miracles of Human Language: An Introduction to Linguistics",
    provider: "Coursera",
    description: "Learn how sounds represent ideas, why dialects vary, and explore minority languages that maintain thousands of years of morphological history.",
    url: "https://www.coursera.org/learn/human-language",
    tags: ["Linguistics", "Language Preservation", "Phonology"],
    level: "Beginner"
  },
  {
    id: "coursera-tibetan-culture",
    title: "Introduction to Tibetan Language and Dialects",
    provider: "Coursera",
    description: "Deep study of Classical Tibetan script, vocabulary, grammar paradigms, and their relationship with Western Himalayan dialects like Ladakhi and Purik.",
    url: "https://www.coursera.org/learn/tibetan-buddhist-culture",
    tags: ["Sino-Tibetan", "Himalayan Dialects", "Tibetan Script"],
    level: "Intermediate"
  },
  {
    id: "khan-grammar-syntax",
    title: "Grammar, Syntax, and Structural Typology",
    provider: "Khan Academy",
    description: "Explore word arrangement, dative postpositions, and case modifiers that describe active-ergative relationship structures across various world languages.",
    url: "https://www.khanacademy.org/humanities/grammar",
    tags: ["Grammar Suffixes", "Syntactic Typology", "Self-paced"],
    level: "Beginner"
  },
  {
    id: "res-grokipedia-purgi",
    title: "Grokipedia Purigi Language Guide",
    provider: "Grokipedia",
    description: "Detailed linguistic encyclopedia analyzing the phonology, archaic syntax, and historical vocabulary of the Purgi (Purigi) language spoken in Kargil.",
    url: "https://grokipedia.com/page/Purgi_language",
    tags: ["Purigi Dialect", "Grammar", "Phonetics", "Kargil Valley"],
    level: "Archival"
  },
  {
    id: "res-balti-adab",
    title: "Balti Adab - Language & Literary Archives",
    provider: "Balti Adab",
    description: "A premier cultural preservation initiative hosting Balti texts, poetry databases, orthographic writing manuals, and classical literature collections.",
    url: "https://baltiadab.com/en/balti-language",
    tags: ["Balti Literature", "Preservation", "Poetry", "Skardu"],
    level: "Archival"
  },
  {
    id: "res-openbalti-dict",
    title: "OpenBalti Digital Dictionary",
    provider: "OpenBalti",
    description: "An open, interactive English-Balti digital dictionary compiling extensive vocabulary lists, IPA transcriptions, and cultural references.",
    url: "https://openbalti.com/dictionary",
    tags: ["Dictionary", "Vocabulary", "IPA Guide", "Interactive"],
    level: "Archival"
  }
];
